apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    policies.kyverno.io/last-applied-patches: |
      deployment-has-multiple-replicas.deployment-has-multiple-replicas.kyverno.io: replaced
        /spec/replicas
  creationTimestamp: "2022-03-02T08:52:35Z"
  generation: 1
  labels:
    app: deploy-nginx
  name: deploy-nginx
  namespace: default
  resourceVersion: "34392"
  uid: 98d1e9a8-14ed-4442-9ff1-3c3d4c2341ee
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deploy-nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-nginx
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2022-03-02T08:52:37Z"
    lastUpdateTime: "2022-03-02T08:52:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-03-02T08:52:35Z"
    lastUpdateTime: "2022-03-02T08:52:37Z"
    message: ReplicaSet "deploy-nginx-5c989d59bc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
